# Generated by Django 3.2.1 on 2021-05-05 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.IntegerField()),
                ('authors', models.CharField(max_length=255)),
                ('publishing_company', models.CharField(max_length=255)),
                ('edition', models.IntegerField()),
                ('number_pages', models.IntegerField()),
            ],
        ),
    ]
